version: 0.2

phases:
    install:
        runtime-versions:
          nodejs : 10
    pre_build:
      commands:
        - npm install
    build:
      commands:
        - npm run build:ci
    post_build:
      commands:
        - aws s3 rm s3://${diogosouza} --recursive
        - echo S3 bucket cleared
        - aws s3 cp dist s3://${diogosouza} --recursive
        - echo Build completed on `date`
