version: 0.2
env:
    variables:
        S3_BUCKET: "diogosouza"

phases:
    install:
        runtime-versions:
            nodejs: 10
        commands:
            - npm install -y npm@latest
            - npm install -g @angular/cli
            - rm package-lock.json
    pre_build:
      commands:
        - npm install
    build:
      commands:
        - npm run build:ci
    post_build:
      commands:
        - aws s3 rm s3://${S3_BUCKET} --recursive
        - echo S3 bucket is cleared.
        - aws s3 cp dist s3://${S3_BUCKET} --recursive
        - echo Build completed on `date``
